name: Deploy Portfolio Applicaton to Github pages.

on:
  workflow_dispatch:

jobs:
  build-application:
    runs-on: ubuntu-latest
    outputs:
      build-folder: ${{steps.upload.outputs.artifact}}
    steps:
      - name: Checkout the Code
        uses: actions/checkout@v4

      - name: Setup Node jobs
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Build Applicaton
        run: CI=false npm run build
        env:
          REACT_APP_EMAIL_SERVICE_ID: ${{ secrets.REACT_APP_EMAIL_SERVICE_ID }}
          REACT_APP_EMAIL_TEMPLATE_ID: ${{ secrets.REACT_APP_EMAIL_TEMPLATE_ID }}
          REACT_APP_EMAIL_PUBLIC_KEY: ${{ secrets.REACT_APP_EMAIL_PUBLIC_KEY }}

      - name: Upload the Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build
          path: build

  deploy-application:
    runs-on: ubuntu-latest
    needs: build-application
    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v4
        with:
          name: build
          path: build

      - name: Deploy to Github Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{secrets.GITHUB_TOKEN}}
          publish_dir: ./build
